// flow-typed signature: cb865b5bfafca1517dd7f4f8e9770925
// flow-typed version: <<STUB>>/koa-session-minimal_v^3.0.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-session-minimal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-session-minimal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-session-minimal/dist/memory_store' {
  declare module.exports: any;
}

declare module 'koa-session-minimal/dist/session' {
  declare module.exports: any;
}

declare module 'koa-session-minimal/dist/store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-session-minimal/dist/memory_store.js' {
  declare module.exports: $Exports<'koa-session-minimal/dist/memory_store'>;
}
declare module 'koa-session-minimal/dist/session.js' {
  declare module.exports: $Exports<'koa-session-minimal/dist/session'>;
}
declare module 'koa-session-minimal/dist/store.js' {
  declare module.exports: $Exports<'koa-session-minimal/dist/store'>;
}
