// flow-typed signature: 7f670723e3bc66f6da7de7ac6b535668
// flow-typed version: <<STUB>>/koa-static-cache_v^5.1.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-static-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-static-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-static-cache/index' {
  declare module.exports: $Exports<'koa-static-cache'>;
}
declare module 'koa-static-cache/index.js' {
  declare module.exports: $Exports<'koa-static-cache'>;
}
