// flow-typed signature: aa505cd51f6730ce0eae16ad8065a2ae
// flow-typed version: <<STUB>>/react-test-utils_v^0.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-test-utils/ReactTestUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-test-utils/index' {
  declare module.exports: $Exports<'react-test-utils'>;
}
declare module 'react-test-utils/index.js' {
  declare module.exports: $Exports<'react-test-utils'>;
}
declare module 'react-test-utils/ReactTestUtils.js' {
  declare module.exports: $Exports<'react-test-utils/ReactTestUtils'>;
}
