// flow-typed signature: 1652f85f10c721907f474027dce71107
// flow-typed version: <<STUB>>/babel-plugin-import-inspector_v>=2.0.0 <3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-import-inspector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-import-inspector' {
  declare module.exports: any;
}
