// flow-typed signature: b106baeb4737776657ed02ad0d4f2db3
// flow-typed version: <<STUB>>/babel-plugin-styled-components_v^1.1.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-styled-components' {
  declare module.exports: any;
}
