// flow-typed signature: dabb590d20b103aa08a2a8c266140e0d
// flow-typed version: <<STUB>>/babel-preset-spust_v^1.0.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-spust'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-spust' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-spust/client' {
  declare module.exports: any;
}

declare module 'babel-preset-spust/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-spust/client.js' {
  declare module.exports: $Exports<'babel-preset-spust/client'>;
}
declare module 'babel-preset-spust/index' {
  declare module.exports: $Exports<'babel-preset-spust'>;
}
declare module 'babel-preset-spust/index.js' {
  declare module.exports: $Exports<'babel-preset-spust'>;
}
declare module 'babel-preset-spust/server.js' {
  declare module.exports: $Exports<'babel-preset-spust/server'>;
}
