// flow-typed signature: 1a644edf6ac5214cc7eb32dabeab0a7d
// flow-typed version: <<STUB>>/caniuse-db_v^1.0.30000697/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'caniuse-db' {
  declare module.exports: any;
}
