// flow-typed signature: 4dc1f97f811b1b5943fc66efd9c4ee67
// flow-typed version: <<STUB>>/import-inspector_v>=2.0.0 <3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-inspector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-inspector' {
  declare module.exports: any;
}
