// flow-typed signature: 6727c21f245a498a62aff5e604cd2c1e
// flow-typed version: <<STUB>>/offline-plugin_v>=4.8.1 <5.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'offline-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'offline-plugin' {
  declare module.exports: any;
}
