// flow-typed signature: 79b914db66132e910b487a6cc04e12b6
// flow-typed version: <<STUB>>/port-pid_v^0.0.6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'port-pid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'port-pid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'port-pid/index' {
  declare module.exports: $Exports<'port-pid'>;
}
declare module 'port-pid/index.js' {
  declare module.exports: $Exports<'port-pid'>;
}
