// flow-typed signature: 3cfc1c3731f6df61e233c5388fe61bf9
// flow-typed version: <<STUB>>/react-loadable_v>=4.0.0 <5.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loadable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loadable' {
  declare module.exports: any;
}
