// flow-typed signature: 8cf7cb8d199a2060f69f3e4e84be2504
// flow-typed version: <<STUB>>/styled-components_v>=2.0.0 <3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
}
