// flow-typed signature: 507cbea0b4b18514ab71a8178686a60c
// flow-typed version: <<STUB>>/toposort_v^1.0.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'toposort'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'toposort' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'toposort/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'toposort/index' {
  declare module.exports: $Exports<'toposort'>;
}
declare module 'toposort/index.js' {
  declare module.exports: $Exports<'toposort'>;
}
declare module 'toposort/test.js' {
  declare module.exports: $Exports<'toposort/test'>;
}
